kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: naughty-saraswati-f33bdeb010-scaler
  namespace: apps-release
spec:
  hosts:
    - cc1fbde45ead-in-south-01.mayson.dev
  pathPrefixes:
    - /eu-west-2-backstractelb-fa627b-coll-5b470af4607143dfa3320626b0520f2a/ # e.g. /infallible-naveen-... naughty-saraswati-f33bdeb010/
  scaleTargetRef:
    name: naughty-saraswati-f33bdeb010-depl
    kind: Deployment
    apiVersion: apps/v1
    service: naughty-saraswati-f33bdeb010-srv # e.g. coll-8a2a...-srv
    port: 80
  replicas:
    min: 0
    max: 10
  scaledownPeriod: 120 #inseconds
  scalingMetric:
    requestRate:
      targetValue: 100
      window: 1m